version: "3.9"

services:
  database:
    image: postgres
    container_name: database_duel_monsters
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user_duel_monsters
      - POSTGRES_PASSWORD=password_duel_monsters
      - POSTGRES_DB=db_duel_monsters
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: duel_monsters
    # restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
